import { useEffect } from 'react';

export const useScrollAnimation = (loading) => {
  useEffect(() => {
      if (loading) return;

          const animateNavbar = () => {
                const navbar = document.querySelector('.navbar');
                      if (navbar) {
                              navbar.classList.add('animate');
                                    }
                                        };

                                            const animateHeroText = () => {
                                                  const heroName = document.querySelector('.hero-name');
                                                        const heroSubFixed = document.querySelector('.hero-sub-right-fixed');
                                                              const heroSub2 = document.querySelector('.hero-sub-right2');

                                                                    if (heroName) {
                                                                            setTimeout(() => heroName.classList.add('animate'), 400);
                                                                                  }
                                                                                        if (heroSubFixed) {
                                                                                                setTimeout(() => heroSubFixed.classList.add('animate'), 600);
                                                                                                      }
                                                                                                            if (heroSub2) {
                                                                                                                    setTimeout(() => heroSub2.classList.add('animate'), 600);
                                                                                                                          }
                                                                                                                              };

                                                                                                                                  const createScrollObserver = () => {
                                                                                                                                        const standardObserverOptions = {
                                                                                                                                                threshold: 0.15,
                                                                                                                                                        rootMargin: '0px 0px -50px 0px',
                                                                                                                                                              };

                                                                                                                                                                    const standardObserver = new IntersectionObserver((entries) => {
                                                                                                                                                                            entries.forEach(entry => {
                                                                                                                                                                                      if (entry.isIntersecting) {
                                                                                                                                                                                                  entry.target.classList.add('animate');
                                                                                                                                                                                                              standardObserver.unobserve(entry.target);

                                                                                                                                                                                                                          // Animate children inside about-grid
                                                                                                                                                                                                                                      if (entry.target.classList.contains('about-grid')) {
                                                                                                                                                                                                                                                    const aboutText = entry.target.querySelector('.about-text');
                                                                                                                                                                                                                                                                  const aboutImage = entry.target.querySelector('.about-image');
                                                                                                                                                                                                                                                                                if (aboutText) aboutText.classList.add('animate');
                                                                                                                                                                                                                                                                                              if (aboutImage) aboutImage.classList.add('animate');
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                      // Animate children inside skills-grid
                                                                                                                                                                                                                                                                                                                                  if (entry.target.classList.contains('skills-grid')) {
                                                                                                                                                                                                                                                                                                                                                const skillItems = entry.target.querySelectorAll('.skill-item');
                                                                                                                                                                                                                                                                                                                                                              skillItems.forEach(item => item.classList.add('animate'));
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                      // Animate children inside ANY projects-grid (web, game, mobile)
                                                                                                                                                                                                                                                                                                                                                                                                  if (entry.target.classList.contains('projects-grid')) {
                                                                                                                                                                                                                                                                                                                                                                                                                const projectCards = entry.target.querySelectorAll('.project-card');
                                                                                                                                                                                                                                                                                                                                                                                                                              projectCards.forEach(card => card.classList.add('animate'));
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, standardObserverOptions);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Hero image gets its own observer with different thresholds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const heroImageObserverOptions = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      threshold: 0.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rootMargin: '0px 0px -200px 0px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const heroImageObserver = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        entry.target.classList.add('animate');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    heroImageObserver.unobserve(entry.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, heroImageObserverOptions);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // --- Observe section titles ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const sectionTitles = document.querySelectorAll('.section-title');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sectionTitles.forEach(title => standardObserver.observe(title));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- FIX: Observe ALL .projects-grid elements, not just the first one ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const allProjectsGrids = document.querySelectorAll('.projects-grid');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                allProjectsGrids.forEach(grid => standardObserver.observe(grid));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // --- Observe about grid ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const aboutGrid = document.querySelector('.about-grid');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (aboutGrid) standardObserver.observe(aboutGrid);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- Observe skills grid ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const skillsGrid = document.querySelector('.skills-grid');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (skillsGrid) standardObserver.observe(skillsGrid);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // --- Observe contact ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const contactContainer = document.querySelector('.contact-container');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (contactContainer) standardObserver.observe(contactContainer);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // --- Observe footer ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const footer = document.querySelector('.footer');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (footer) standardObserver.observe(footer);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // --- Observe hero image (special observer) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const heroImage = document.querySelector('.hero-image');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (heroImage) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  heroImageObserver.observe(heroImage);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { standardObserver, heroImageObserver };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const timer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            animateNavbar();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  animateHeroText();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        createScrollObserver();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 100);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [loading]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default useScrollAnimation;