import React, { useState, useEffect } from "react";

export default function Navbar() {
  const [open, setOpen] = useState(false);
    const [scrolled, setScrolled] = useState(false);

      useEffect(() => {
          const onScroll = () => setScrolled(window.scrollY > 40);
              window.addEventListener("scroll", onScroll);
                  return () => window.removeEventListener("scroll", onScroll);
                    }, []);

                      const scrollToSection = (sectionId) => {
                          console.log("Clicked:", sectionId);
                              
                                  // Close menu
                                      setOpen(false);
                                          
                                              // Try multiple methods to scroll
                                                  const scrollMethods = () => {
                                                        const section = document.getElementById(sectionId);
                                                              console.log("Section found:", section);
                                                                    
                                                                          if (!section) {
                                                                                  console.error("Section not found:", sectionId);
                                                                                          return;
                                                                                                }

                                                                                                      // Method 1: scrollIntoView (most reliable)
                                                                                                            section.scrollIntoView({ 
                                                                                                                    behavior: 'smooth', 
                                                                                                                            block: 'start' 
                                                                                                                                  });
                                                                                                                                        
                                                                                                                                              // Adjust for navbar after scrollIntoView
                                                                                                                                                    setTimeout(() => {
                                                                                                                                                            const navbarHeight = 90;
                                                                                                                                                                    const currentScroll = window.pageYOffset;
                                                                                                                                                                            window.scrollTo({
                                                                                                                                                                                      top: currentScroll - navbarHeight,
                                                                                                                                                                                                behavior: 'smooth'
                                                                                                                                                                                                        });
                                                                                                                                                                                                              }, 100);
                                                                                                                                                                                                                  };

                                                                                                                                                                                                                      // Execute after a short delay
                                                                                                                                                                                                                          setTimeout(scrollMethods, 150);
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                  <header className={`navbar ${scrolled ? "scrolled" : ""}`}>
                                                                                                                                                                                                                                        <div className="nav-inner">
                                                                                                                                                                                                                                                {/* Logo */}
                                                                                                                                                                                                                                                        <div 
                                                                                                                                                                                                                                                                  className="brand" 
                                                                                                                                                                                                                                                                            onClick={() => scrollToSection("home")}
                                                                                                                                                                                                                                                                                      style={{ cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                        <div className="logo-circle">
                                                                                                                                                                                                                                                                                                                    <p>O</p>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                              {/* Hamburger */}
                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                className={`hamburger ${open ? "active" : ""}`}
                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setOpen(!open)}
                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                            <span></span>
                                                                                                                                                                                                                                                                                                                                                                                                      <span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                <span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Navigation */}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <nav className={`nav ${open ? "open" : ""}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="nav-link" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => scrollToSection("home")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="nav-link" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => scrollToSection("projects")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Projects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="nav-link" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => scrollToSection("about")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    About
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="nav-link" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => scrollToSection("skills")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Skills
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="contact-button" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => scrollToSection("contact")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Contact Me
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }